import com.sun.glass.events.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection conn = null;
    
    public Login() {
        
        initComponents();
        current_date();
        conn = DB.java_db();
    }
    
    // current date and time 
    public void current_date()
    {   
        Thread thread = new Thread(){
            @Override
            public void run() {
                try {
                    while (true) {
                    GregorianCalendar gc = new GregorianCalendar();
                    int hour = gc.get(Calendar.HOUR);
                    int minute = gc.get(Calendar.MINUTE);
                    int second = gc.get(Calendar.SECOND);
                    int meridiem = gc.get(Calendar.AM_PM);
                    
                    // date
                    int day = gc.get(Calendar.DAY_OF_MONTH);
                    int month = gc.get(Calendar.MONTH);
                    int year = gc.get(Calendar.YEAR);
                    
                    // display time and date
                    if (minute < 10) {
                        lbl_time.setText(hour + ":" + "0" + minute + ":" + second + " " + (meridiem == 0 ? "AM" : "PM"));
                    }
                    else {
                        lbl_time.setText(hour + ":" + minute + ":" + second + " " + (meridiem == 0 ? "AM" : "PM"));
                    }
                    
                    lbl_date.setText(day + "-" + monthName(month) + "-" + year);
                    
                    sleep(1000);
                    
                }
                }
                catch (InterruptedException e) {
                }
            }
        };
        
        thread.start();
    }
    
    public String monthName(int num)
    {
        String[] month = new String[]{"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        return month[num];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_signup = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbl_heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmforgetpassword = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payroll Management System");
        setResizable(false);

        main.setBackground(new java.awt.Color(29, 101, 166));
        main.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(29, 101, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 12), new java.awt.Color(244, 243, 244))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 242, 234));
        jLabel4.setText("Password");

        btn_login.setBackground(new java.awt.Color(200, 214, 202));
        btn_login.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btn_login.setForeground(new java.awt.Color(44, 62, 80));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lll.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        txt_username.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(4, 12, 14));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 242, 234));
        jLabel3.setText("Username");

        btn_signup.setBackground(new java.awt.Color(200, 214, 202));
        btn_signup.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(44, 62, 80));
        btn_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cre2.png"))); // NOI18N
        btn_signup.setText("SignUp");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        txt_pass.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ulog.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(txt_username)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(29, 101, 166));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jbl_heading.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jbl_heading.setForeground(new java.awt.Color(235, 242, 234));
        jbl_heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/m.png"))); // NOI18N
        jbl_heading.setText("  Payroll Management System");

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 243, 243));
        jLabel1.setText("Date");

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 243, 243));
        jLabel7.setText("Time");

        lbl_date.setFont(new java.awt.Font("Verdana", 3, 13)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(235, 242, 234));
        lbl_date.setText("Date");

        lbl_time.setFont(new java.awt.Font("Verdana", 3, 13)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(235, 242, 234));
        lbl_time.setText("Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbl_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lbl_time))))
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jMenu1.setForeground(new java.awt.Color(40, 39, 38));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jmforgetpassword.setText("Help");
        jmforgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmforgetpasswordActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Forget Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmforgetpassword.add(jMenuItem1);
        jmforgetpassword.add(jSeparator1);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmforgetpassword.add(jMenuItem2);

        jMenuBar1.add(jmforgetpassword);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_signupActionPerformed

    private void jmforgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmforgetpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmforgetpasswordActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/images/forgetpass.png");
        String id = (String)JOptionPane.showInputDialog(null, "Enter your ID: ", "Forget Password", JOptionPane.INFORMATION_MESSAGE, icon, null, null);
        
        try
        {
            String selectQuery = "select username, password from paydb.newaccount where id = ?";
            PreparedStatement sps = conn.prepareStatement(selectQuery);
            sps.setString(1, id);
            ResultSet srs = sps.executeQuery();
            srs.next();
            String user = srs.getString("username");
            String pass = srs.getString("password");
            JOptionPane.showMessageDialog(null, ("Username : " + user + "\nPassword : " + pass));
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
       try
       {
           String selectQuery = "select username, password from paydb.newaccount";
           PreparedStatement pst = conn.prepareStatement(selectQuery);
           ResultSet rs = pst.executeQuery();
           
           ArrayList<String> ulist = new ArrayList();
           ArrayList<String> plist = new ArrayList();
           
           while (rs.next())
           {
               String user = rs.getString("username");
               String pass = rs.getString("password");
               
               ulist.add(user);
               plist.add(pass);
           }
           
           // validation
           if (ulist.contains(txt_username.getText()) && plist.contains(txt_pass.getText()))
           {
               try
               {
                   String selectQuery2 = "select id, firstname, surname from paydb.newaccount where username = ?";
                   PreparedStatement spst = conn.prepareStatement(selectQuery2);
                   spst.setString(1, txt_username.getText());
                   ResultSet srs = spst.executeQuery();
                   srs.first();
                   
                   String aid = srs.getString(1);
                   Admin.id = aid;
                   String fn = srs.getString(2);
                   Admin.firstname = fn;
                   String sn = srs.getString(3);
                   Admin.lastname = sn;
               }
               catch (SQLException e)
               {
                   JOptionPane.showMessageDialog(null, e);
               }
               
               // navigating the main menu
               this.dispose();
               JOptionPane.showMessageDialog(null, "Login Success!");
               new MainMenu().setVisible(true);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Username and Password you entered are wrong!","Error", JOptionPane.ERROR_MESSAGE);
           }
       }
       catch (SQLException e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
             try
            {
                 String selectQuery = "select username, password from paydb.newaccount";
                PreparedStatement pst = conn.prepareStatement(selectQuery);
                ResultSet rs = pst.executeQuery();
           
                ArrayList<String> ulist = new ArrayList();
                ArrayList<String> plist = new ArrayList();
           
                while (rs.next())
                {
                    String user = rs.getString("username");
                    String pass = rs.getString("password");
               
                    ulist.add(user);
                    plist.add(pass);
                }
           
                // validation
                if (ulist.contains(txt_username.getText()) && plist.contains(txt_pass.getText()))
                {
                    try
                    {
                        String selectQuery2 = "select id, firstname, surname from paydb.newaccount where username = ?";
                        PreparedStatement spst = conn.prepareStatement(selectQuery2);
                        spst.setString(1, txt_username.getText());
                        ResultSet srs = spst.executeQuery();
                        srs.first();
                   
                        String aid = srs.getString(1);
                        Admin.id = aid;
                        String fn = srs.getString(2);
                        Admin.firstname = fn;
                        String sn = srs.getString(3);
                        Admin.lastname = sn;
                    }
                    catch (SQLException e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
               
                    // navigating the main menu
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Login Success!");
                    new MainMenu().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Username and Password you entered are wrong!","Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (SQLException e)
           {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_txt_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel jbl_heading;
    private javax.swing.JMenu jmforgetpassword;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JPanel main;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
