/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gautam Sarkar
 */

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    Connection conn = null;
    
    public Register() {
        initComponents();
        conn = DB.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        txt_surname = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(244, 243, 244));
        desktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel1.setBackground(new java.awt.Color(244, 243, 244));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Create New Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 12), new java.awt.Color(44, 62, 80))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_surname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(44, 62, 80));
        txt_surname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 210, 30));

        txt_firstname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_firstname.setForeground(new java.awt.Color(44, 62, 80));
        txt_firstname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 210, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 39, 38));
        jLabel6.setText("Contact");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, 30));

        txt_contact.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(44, 62, 80));
        txt_contact.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactKeyTyped(evt);
            }
        });
        panel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 210, 30));

        btn_create.setBackground(new java.awt.Color(200, 214, 202));
        btn_create.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_create.setForeground(new java.awt.Color(40, 39, 38));
        btn_create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cre2.png"))); // NOI18N
        btn_create.setText("Create ");
        btn_create.setBorder(null);
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        panel1.add(btn_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 110, 35));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 39, 38));
        jLabel3.setText("Username");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 39, 38));
        jLabel4.setText("Password");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 39, 38));
        jLabel1.setText("First Name");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 39, 38));
        jLabel2.setText("Surname");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, 30));

        txt_password.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_password.setForeground(new java.awt.Color(44, 62, 80));
        txt_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        panel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 210, 30));

        txt_username.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(44, 62, 80));
        txt_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 210, 30));

        jPanel1.setBackground(new java.awt.Color(244, 243, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 54, 37));
        jLabel7.setText("New Account For Administrator");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(160, 160, 160)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(263, 263, 263))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // date
        GregorianCalendar gc = new GregorianCalendar();
        String[] monthName = new String[]{"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        int day = gc.get(Calendar.DAY_OF_MONTH);
        int month = gc.get(Calendar.MONTH);
        int year = gc.get(Calendar.YEAR);
        String date = day + "-" + monthName[month] + "-" + year;
        
        // id
        String adminId = new IDGeneration().getID();
        
        try
        {
            String selectQuery = "select username from paydb.newaccount";
            PreparedStatement pst = conn.prepareStatement(selectQuery);
            ResultSet rs = pst.executeQuery();
            
            ArrayList<String> list = new ArrayList();
            while (rs.next())
            {
                String un = rs.getString("username");
                list.add(un);
            }
            
            // validation 
            if (list.contains(txt_username.getText()))
            {
                JOptionPane.showMessageDialog(null, "Another user with this username already exists!");
            }
            else
            {
                String insertQuery = "insert into paydb.newaccount values(?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ipst = conn.prepareStatement(insertQuery);
                ipst.setString(1, adminId);
                ipst.setString(2, txt_firstname.getText());
                ipst.setString(3, txt_surname.getText());
                ipst.setString(4, txt_username.getText());
                ipst.setString(5, txt_password.getText());
                ipst.setLong(6, Long.valueOf(txt_contact.getText()));
                ipst.setString(7, date);
                ipst.executeUpdate();
                
                // success report
                JOptionPane.showMessageDialog(null,("Account Created!" + "\nYour ID: " + adminId + "\nUsername: " + txt_username.getText() + "\nPassword: " + txt_password.getText()));
                new Login().setVisible(true);
                this.dispose();
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_contactKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JPanel desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

}
